{{- range $app_name, $app := .Values.apps }}
{{- range $env := $app }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: app-{{ $app_name }}-{{ $env }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limit-range
  namespace: app-{{ $app_name }}-{{ $env }}
spec:
  limits:
  - default:
      cpu: 0.2
      memory: 128Mi
    type: Container
{{- end }}
{{- end }}
